[project]
name = "cs4803-eml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "thop>=0.1.1.post2209072238",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
